name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Build Makefile
      env: # Currently BOOST_ROOT is defined but not installed: https://github.com/actions/virtual-environments/issues/83
        BOOST_ROOT:
      run: | # Also no bison at the moment: https://github.com/actions/virtual-environments/issues/86
        sudo apt install bison
        pwd
        cd code
        make
        make check
